[package]
name = "algorithms"
version = "0.1.0"
authors = ["asuradev99 <ethanaditya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
num = "0.4.0"
